### ISSUE TITLE
Bugs in denormaliseTaxa()

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#129] opened 2017-02-23 00:45 UTC
1. output shows incorrect percentage values:

```
Getting species groups
Starting denormalisation scan for offline index
Clearing existing denormalisations
Cleared 5000 taxa (8%)
Cleared 10000 taxa (18%)
Cleared 15000 taxa (29%)
Cleared 20000 taxa (43%)
Cleared 25000 taxa (61%)
Cleared 30000 taxa (83%)
Cleared 35000 taxa (113%)
Cleared 40000 taxa (153%)
Cleared 45000 taxa (213%)
Cleared 50000 taxa (310%)
Cleared 55000 taxa (495%)
Cleared 60000 taxa (983%)
Cleared 61104 taxa (5535%)
```

So it seems something funny is hapenning with number of docs and `rows` param sent and `numFound` in response.

2. In the section "Denormalising top-level taxa", the [following code](https://github.com/AtlasOfLivingAustralia/bie-index/blob/master/grails-app/services/au/org/ala/bie/ImportService.groovy#L1704) looks wrong:

```
def buffer = []
docs.each { doc ->
    denormaliseEntry(doc, [:], [], [], buffer, bufferLimit, pageSize, online, js, speciesGroupMapper)
}
processed++
if (!buffer.isEmpty())
    indexService.indexBatch(buffer, online)
if (total > 0 && processed % 1000 == 0) {
    def percentage = Math.round(processed * 100 / total)
    log("Denormalised ${processed} dangling taxa (${percentage}%)")
}
```

all the processing & indexing (SOLR) is happening inside in the `denormaliseEntry` method, it is doing its own commit on the `buffer` list passed in, so there is no point on also trying to `indexBatch` the buffer in the code shown above (?). Compare this with the other sections in this method, where the last 7 lines above appear inside the `docs.each`.

3. The [`denormaliseEntry` method](https://github.com/AtlasOfLivingAustralia/bie-index/blob/71698375ede198d90ae63c949eac0a137ea90a0e/grails-app/services/au/org/ala/bie/ImportService.groovy#L1798) appears to be [recursive](https://github.com/AtlasOfLivingAustralia/bie-index/blob/71698375ede198d90ae63c949eac0a137ea90a0e/grails-app/services/au/org/ala/bie/ImportService.groovy#L1862), which might account for the very long load times for this service

**Comment by nickdos** [comment] 2017-02-23 03:58
Also this process is very slow running on my machine - it's been going for 4 hours now and hasn't finished yet (it is still doing stuff though). I'm wondering if there are unnecessary requests happening (particularly in the nested `denormaliseEntry` call?) or if the process might be improved in some way?

**Comment by adam-collins** [comment] 2023-12-12 21:22
1 is fixed. 

2 looks OK today because there are no duplicate commit. `denormaliseEntry` commits and clears the buffer when at the bufferLimit. After calling `denormaliseEntry` any remaining (uncommitted) buffer contents are committed.

3. The top level `-parentGuid:*` loop is followed by a `parentGuid:{guid}` loop. Loops caused by the incorrect data `record.guid == recored.parentGuid` are prevented using the `stack` parameter.

**Closed by adam-collins** 2023-12-12 21:22 UTC
