### ISSUE TITLE
Taxon page `imageIdentifier` is incorrectly set or not updated 

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/bie-index#341] opened 2021-10-25 01:41 UTC
Previously reported https://github.com/AtlasOfLivingAustralia/bie-plugin/issues/231.

This taxon https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/node/apni/2919311.json

shows `"imageIdentifier" : "16464424-9492-4683-8277-a2c44b41334a",`

The problem is the [gallery view for that taxon](https://bie.ala.org.au/species/https:/id.biodiversity.org.au/node/apni/2919311#gallery), does not include [the record](https://biocache.ala.org.au/occurrences/3f168150-e101-4ec0-85a7-e6d73ac15c2c) for [that imageId](https://images.ala.org.au/image/16464424-9492-4683-8277-a2c44b41334a), due to that record having been flagged by a user with a taxonomic issue. 

It seems this value is being stored in the BIE SOLR index (guess) and thus was not updated when the record/image was flagged. Note, that image is NOT defined in the "ALA Preferred species images" [list](https://lists.ala.org.au/speciesListItem/list/dr4778).

Would be good if hero image was either not stored/cached or else if it isn't, then the same biocache-service call that generates the gallery, is used to determine the `imageIdentifier` value (that respects the user annotations).

**Comment by TaniaGLaity** [comment] 2023-12-06 05:11
duplicate of existing issue

**Closed as completed by TaniaGLaity** 2023-12-06 05:11 UTC
Labels: bug
