### ISSUE TITLE
No Worms category

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/bie-index#227] opened 2019-01-21 05:41 UTC
This comes originally from 
 
https://support.ehelp.edu.au/a/tickets/27235

The point about no worms listed (also applies to many other lower taxa e.g. Protista, Bryozoa, Nematoda, Annelida etc. etc.). When trying to ‘Record a sighting’ under ‘Identification tags’ many groups are listed but nothing lower than Molluscs.

**Comment by adam-collins** [comment] 2023-12-13 00:56
Duplicate of https://github.com/AtlasOfLivingAustralia/bie-index/issues/104

**Closed by adam-collins** 2023-12-13 00:56 UTC
Labels: enhancement, IAD
