### ISSUE TITLE
Preferred source of images for taxon

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/bie-index#213] opened 2018-10-29 23:04 UTC
Allow a data resource to be marked as a preferred source so that images from that source get bumped to the top.

Expected to be useful for images from curated collections where there are a set of ideal images for various lifecycles. Eg. for butterflies, diagnostic, adult, egg, lava, pupa. These should be the first ones in the gallery. (Slightly different to the single hero shot in that there are several key images which just need to float to the top in the gallery although this is obviously where the main image comes from.)

**Comment by adam-collins** [comment] 2023-12-13 01:11
Duplicate of closed issue https://github.com/AtlasOfLivingAustralia/bie-index/issues/3

**Closed by adam-collins** 2023-12-13 01:11 UTC
Labels: enhancement
